INSERT INTO plantas (idplanta, nombre, descripcion, imagen) VALUES
(1, 'LAVANDA', 'La Lavanda es una de las plantas aromáticas por excelencia, perfecta para tener en casa. Los cuidados de la lavanda no son demasiado complicados; y no solo nos proporcionan el placer de disfrutar de la belleza natural de esta planta sino, además, su mayor virtud: su peculiar e irresistible perfume.', 'https://mygarden.com.co/wp-content/uploads/2020/05/PLANTA-LAVANDA-2--300x300.jpg'),
(2, 'NOVIOS', 'Son plantas de jardín exterior de mucho colorido especiales para tener en materas colgantes en una terraza, patio o balcón. Vienen en una variedad de colores y son fáciles de cuidar, lo que los convierte en favoritos de muchos para decorar.', 'https://mygarden.com.co/wp-content/uploads/2020/01/PLANTA-GERANIO-PELARGONIUM.-2-JPG-300x300.jpg'),
(3, 'ALBAHACA', 'A la hora de cuidar una planta de albahaca, tienes que ser consciente de que se trata de una planta de temporada y que, por tanto, una vez terminado su ciclo, se secará y morirá.', 'https://mygarden.com.co/wp-content/uploads/2020/01/PLANTA-ALBAHACA-2-300x300.png'),
(4, 'LENGUA DE SUEGRA', 'La lengua de suegra, también conocida como sansevieria, es una planta resistente y fácil de cuidar que requiere pocos cuidados.', 'https://mygarden.com.co/wp-content/uploads/2020/07/macetas-boho-7-300x300.jpg'),
(5, 'DALIA', 'La dalia es una planta de floración vistosa y relativamente fácil de cuidar. Prefiere la luz solar directa y un suelo bien drenado. Riega regularmente, manteniendo el suelo húmedo pero no empapado. Fertiliza cada 2-4 semanas durante la temporada de crecimiento con un fertilizante balanceado. Puedes propagarla mediante tubérculos, asegurándote de plantar cada sección con al menos un ojo. Las dalias prosperan en climas cálidos, pero debes protegerlas de las heladas.', 'https://mygarden.com.co/wp-content/uploads/2020/01/PLANTA-DALIA-300x300.jpg'),
(6, 'BUGANVILIA', 'La buganvilla es una planta trepadora que requiere pocos cuidados, pero es importante tener en cuenta algunos aspectos para que florezca de forma óptima.', 'https://mygarden.com.co/wp-content/uploads/2020/05/PLANTA-BOUGANVILLEA-2--300x300.jpg'),
(7, 'PETUNIA LARGA VIDA', 'Las petunias necesitan pleno sol o se volverán delgadas. No suelen florecer a la sombra. Son bastante versátiles y crecen en diferentes tipos de suelo, pero es importante que el suelo drene bien y no permanezca húmedo. Lo mejor es comprar las plantas jóvenes en un vivero que suele vender petunias en pisos.', 'https://mygarden.com.co/wp-content/uploads/2020/01/PLANTA-PETUNIA-LARGA-VIDA-300x300.jpg'),
(8, 'HIERBABUENA', 'La hierbabuena es una planta aromática que no requiere cuidados intensivos, pero necesita algunos cuidados básicos para que crezca sana y fuerte.', 'https://mygarden.com.co/wp-content/uploads/2020/01/HIERBABUENA.png'),
(9, 'AJÍ CAPSICUM', 'Las plantas de ají necesitan agua regularmente para mantenerse hidratadas y promover un crecimiento saludable, pero es importante evitar regar en exceso, ya que el encharcamiento del suelo puede provocar pudrición de las raíces y otras enfermedades relacionadas con el agua.', 'https://mygarden.com.co/wp-content/uploads/2020/01/AJI-CAPSICUM-300x300.jpg'),
(10, 'KALANCHOE', 'El Kalanchoe necesita poder crecer con total libertad, por lo que necesita disponer de un espacio bastante generoso. Aunque algunas variedades crecen sólo unos pocos centímetros, hay otras especies que pueden llegar a medir más de un metro de altura.', 'https://mygarden.com.co/wp-content/uploads/2020/01/PLANTA-KALANCHOE-3--300x300.jpg'),
(11, 'BEGONIA SEMPERFLORENS', 'La Begonia semperflorens es una planta fácil de cuidar. Prefiere la semisombra o lugares bien iluminados sin sol directo. Necesita un suelo con buen drenaje y fértil, y riego regular, manteniendo el suelo húmedo pero no encharcado. Fertiliza cada 2 semanas durante la temporada de crecimiento. Puedes propagarla por semillas o esquejes de tallo. No requiere poda regular y prospera en lugares cálidos y con buena humedad.', 'https://mygarden.com.co/wp-content/uploads/2020/05/PLANTA-BEGONIA-SEMPERFLORENS-2-.jpg'),
(12, 'ROMERO', 'El Romero es una planta aromática muy fácil de cuidar. Necesita mucha luz solar directa y un suelo bien drenado. Riega moderadamente, permitiendo que el suelo se seque entre riegos. Es resistente a la sequía y no requiere fertilización frecuente, pero puedes añadir un poco de compost en primavera. Propágalo mediante esquejes en verano o primavera. Es ideal para climas cálidos y bien ventilados, y tolera el frío moderado.', 'https://mygarden.com.co/wp-content/uploads/2020/05/rosmarinus-officinalis-potted-plant__0539122_PE654563_S5.jpg'),
(13, 'ZINNIA', 'La Zinnia es una planta de floración fácil de cuidar. Requiere mucha luz solar directa y un suelo bien drenado. Riega moderadamente, permitiendo que el suelo se seque entre riegos. Fertiliza con un fertilizante balanceado cada mes durante la temporada de crecimiento. Puedes propagarla mediante semillas en primavera. Las zinnias prosperan en climas cálidos y toleran bien el calor y la sequía.', 'https://mygarden.com.co/wp-content/uploads/2020/05/PLANTA-ZINNIA-300x300.jpg'),
(14, 'BIFLORA', 'La Biflora, también conocida como Milla biflora o Mexican Star, es una planta bulbosa perenne que prefiere la luz solar directa y temperaturas moderadas. Riega con moderación, permitiendo que el suelo se seque casi por completo entre riegos. Utiliza un suelo bien drenado y fertiliza con un fertilizante balanceado cada dos semanas durante la temporada de crecimiento. Puedes propagarla dividiendo los bulbos durante su período de latencia en invierno o primavera. No requiere poda regular y es ideal para xeriscapes y jardines rocosos.', 'https://mygarden.com.co/wp-content/uploads/2020/05/PLANTA-BIFLORA-300x300.jpg'),
(15, 'ALBAHACA MORADA', 'La albahaca morada, también conocida como albahaca morada opal u albahaca púrpura, es una hierba fácil de cultivar. Necesita mucha luz solar directa y un suelo bien drenado. Riega moderadamente, manteniendo el suelo ligeramente húmedo pero no encharcado. Fertiliza cada 4-6 semanas durante la temporada de crecimiento con un fertilizante orgánico. Se puede propagar por semillas o esquejes en primavera. Esta planta es ideal para climas cálidos y añade un toque colorido y aromático a tu jardín o cocina.', 'https://mygarden.com.co/wp-content/uploads/2020/05/PLANTA-AROMATICA-ALBAHACA-MORADA-2--300x300.jpg');


INSERT INTO eventos (ideventos, descripcion) VALUES
(1, 'Regar una planta'),
(2, 'Fertilizar tierra'),
(3, 'Plantar planta'),
(4, 'Podar planta'),
(5, 'Trasplantar planta');
